public class Arithmeticcalculations {
    public void additionMethod(integer x, integer y){
        integer z = x+y;
        System.debug('Sum of  x + y = ' + z);


    }
    public void subtractionMethod(integer x, integer y){
        Integer z = x-y;
        system.debug('Subtraction of x-y = '+z);
    }
    public void multiplicationMethod(integer x, integer y, integer z){
        Integer w = x*y*z;
        system.debug('Multiplication of x*y*z = '+w);
    }
}
