public class PrimitiveDataTypeDemo2 {
   public void print1(){

    Id id1 = '0018Z00002fQLNlQAO';
        system.debug('print id = ' + id1);

        
        Object obj1 = 'This is a string';
        Object obj2 = 15;
        Object obj3 = '0018Z00002fQLNlQAO';
        Object obj4 = true;
     
       System.debug('obj1 = '+ obj1);
       System.debug('obj2 = '+ obj2);
       System.debug('obj3 = '+ obj3);
       System.debug('obj4 = '+ obj4);
   }
    
}
